wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.8.3
      5: 0.10.28
      8:
      - 1
      - 3
      - 5
activation_cnn:
  desc: null
  value: relu
activation_gru:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 105
cnn_layer_size_1:
  desc: null
  value: 34
cnn_layer_size_2:
  desc: null
  value: 43
dropout:
  desc: null
  value: 0.49482076499671734
epochs:
  desc: null
  value: 50
gru_layer_size_1:
  desc: null
  value: 163
gru_layer_size_2:
  desc: null
  value: 45
learning_rate:
  desc: null
  value: 0.06808645778453015
lookback:
  desc: null
  value: 310.0089751763727
momentum:
  desc: null
  value: 0.95
num_cnn_layers:
  desc: null
  value: 2
num_features:
  desc: null
  value: 9
num_gru_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: sgd
