wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 41
cnn_layer_size_1:
  value: 71
cnn_layer_size_2:
  value: 130
dropout:
  value: 0.1279302346748672
epochs:
  value: 50
gru_layer_size_1:
  value: 69
gru_layer_size_2:
  value: 71
learning_rate:
  value: 0.05922882621570675
lookback:
  value: 524
momentum:
  value: 0.8
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: sgd
