wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 69
cnn_layer_size_1:
  value: 197
cnn_layer_size_2:
  value: 147
dropout:
  value: 0.25386274582339813
epochs:
  value: 50
gru_layer_size_1:
  value: 39
gru_layer_size_2:
  value: 102
learning_rate:
  value: 0.06688633383818561
lookback:
  value: 387
momentum:
  value: 0.9
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: adam
