wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 86
cnn_layer_size_1:
  value: 44
cnn_layer_size_2:
  value: 226
dropout:
  value: 0.3407890395472467
epochs:
  value: 50
gru_layer_size_1:
  value: 210
gru_layer_size_2:
  value: 214
learning_rate:
  value: 0.005639579742810652
lookback:
  value: 586
momentum:
  value: 0.9
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: rmsprop
