wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 256
cnn_layer_size_1:
  value: 72
cnn_layer_size_2:
  value: 104
dataset:
  value: strib
dropout:
  value: 0.3562743156002092
epochs:
  value: 10
gru_layer_size_1:
  value: 50
gru_layer_size_2:
  value: 196
learning_rate:
  value: 0.010370659787089297
lookback:
  value: 744
momentum:
  value: 0.5220828738785559
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
