wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 249
cnn_layer_size_1:
  value: 72
cnn_layer_size_2:
  value: 102
dataset:
  value: kolding
dropout:
  value: 0.4253583718248085
epochs:
  value: 10
gru_layer_size_1:
  value: 69
gru_layer_size_2:
  value: 199
learning_rate:
  value: 0.011542956821584297
lookback:
  value: 744
momentum:
  value: 0.2231179278946988
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 0
optimizer:
  value: sgd
