wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 219
cnn_layer_size_1:
  value: 69
cnn_layer_size_2:
  value: 101
dataset:
  value: kolding
dropout:
  value: 0.4599103820888477
epochs:
  value: 10
gru_layer_size_1:
  value: 45
gru_layer_size_2:
  value: 197
learning_rate:
  value: 0.024923394424840387
lookback:
  value: 744
momentum:
  value: 0.7754471115694828
num_cnn_layers:
  value: 0
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: sgd
