wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 250
cnn_layer_size_1:
  value: 72
cnn_layer_size_2:
  value: 104
dataset:
  value: kolding
dropout:
  value: 0.018265304838042416
epochs:
  value: 10
gru_layer_size_1:
  value: 62
gru_layer_size_2:
  value: 191
learning_rate:
  value: 0.0035326769839099147
lookback:
  value: 744
momentum:
  value: 0.8522771463899708
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
