wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 208
cnn_layer_size_1:
  value: 70
cnn_layer_size_2:
  value: 102
dataset:
  value: kolding
dropout:
  value: 0.42109981846297884
epochs:
  value: 10
gru_layer_size_1:
  value: 40
gru_layer_size_2:
  value: 191
learning_rate:
  value: 0.006892674713992945
lookback:
  value: 744
momentum:
  value: 0.44439765825782684
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
