wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.3
      5: 0.10.28
      8:
      - 1
      - 3
      - 5
activation_cnn:
  desc: null
  value: relu
activation_gru:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 254
cnn_layer_size_1:
  desc: null
  value: 67
cnn_layer_size_2:
  desc: null
  value: 107
dataset:
  desc: null
  value: strib
dropout:
  desc: null
  value: 0.45847686837230717
epochs:
  desc: null
  value: 10
gru_layer_size_1:
  desc: null
  value: 52
gru_layer_size_2:
  desc: null
  value: 188
learning_rate:
  desc: null
  value: 0.0309663952845563
lookback:
  desc: null
  value: 744
momentum:
  desc: null
  value: 0.34665938143263136
num_cnn_layers:
  desc: null
  value: 0
num_features:
  desc: null
  value: 9
num_gru_layers:
  desc: null
  value: 0
optimizer:
  desc: null
  value: d
