wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 161
cnn_layer_size_1:
  value: 61
cnn_layer_size_2:
  value: 185
dropout:
  value: 0.13808317617561044
epochs:
  value: 50
gru_layer_size_1:
  value: 104
gru_layer_size_2:
  value: 188
learning_rate:
  value: 0.07403828794481149
lookback:
  value: 523
momentum:
  value: 0.85
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
