wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 42
cnn_layer_size_1:
  value: 61
cnn_layer_size_2:
  value: 130
dropout:
  value: 0.3530930402352234
epochs:
  value: 50
gru_layer_size_1:
  value: 83
gru_layer_size_2:
  value: 133
learning_rate:
  value: 0.055097437779825856
lookback:
  value: 470
momentum:
  value: 0.9
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: sgd
