wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.3
      5: 0.10.28
      8:
      - 1
      - 3
      - 5
activation_cnn:
  desc: null
  value: relu
activation_gru:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 201
cnn_layer_size_1:
  desc: null
  value: 75
cnn_layer_size_2:
  desc: null
  value: 105
dataset:
  desc: null
  value: kolding
dropout:
  desc: null
  value: 0.03770062046505656
epochs:
  desc: null
  value: 10
gru_layer_size_1:
  desc: null
  value: 46
gru_layer_size_2:
  desc: null
  value: 190
learning_rate:
  desc: null
  value: 0.029068026775151804
lookback:
  desc: null
  value: 744
momentum:
  desc: null
  value: 0.49368544710626955
num_cnn_layers:
  desc: null
  value: 0
num_features:
  desc: null
  value: 9
num_gru_layers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: sgd
