wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.8.3
      5: 0.10.28
      8:
      - 1
      - 3
      - 5
activation_cnn:
  desc: null
  value: relu
activation_gru:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 38
cnn_layer_size_1:
  desc: null
  value: 117
cnn_layer_size_2:
  desc: null
  value: 44
dropout:
  desc: null
  value: 0.4494139223659863
epochs:
  desc: null
  value: 50
gru_layer_size_1:
  desc: null
  value: 205
gru_layer_size_2:
  desc: null
  value: 62
learning_rate:
  desc: null
  value: 0.00956622947381968
lookback:
  desc: null
  value: 509.7042710944755
momentum:
  desc: null
  value: 0.9
num_cnn_layers:
  desc: null
  value: 2
num_features:
  desc: null
  value: 9
num_gru_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: sgd
