wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 72
cnn_layer_size_1:
  value: 240
cnn_layer_size_2:
  value: 112
dropout:
  value: 0.19108131022820857
epochs:
  value: 50
gru_layer_size_1:
  value: 33
gru_layer_size_2:
  value: 121
learning_rate:
  value: 0.041404298987883455
lookback:
  value: 348.69894026409463
momentum:
  value: 0.85
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: rmsprop
