wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 38
cnn_layer_size_1:
  value: 117
cnn_layer_size_2:
  value: 44
dropout:
  value: 0.4494139223659863
epochs:
  value: 50
gru_layer_size_1:
  value: 205
gru_layer_size_2:
  value: 62
learning_rate:
  value: 0.00956622947381968
lookback:
  value: 509.7042710944755
momentum:
  value: 0.9
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
