wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 147
cnn_layer_size_1:
  value: 32
cnn_layer_size_2:
  value: 78
cnn_layer_size_3:
  value: 38
dataset:
  value: kolding
dropout:
  value: 0.08791089961754245
epochs:
  value: 25
gru_layer_size_1:
  value: 133
gru_layer_size_2:
  value: 48
gru_layer_size_3:
  value: 108
learning_rate:
  value: 0.014745383918515442
lookback:
  value: 744
momentum:
  value: 0.7736504000202488
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
