wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 180
cnn_layer_size_1:
  value: 92
cnn_layer_size_2:
  value: 94
cnn_layer_size_3:
  value: 89
dataset:
  value: kolding
dropout:
  value: 0.3128109462373897
epochs:
  value: 25
gru_layer_size_1:
  value: 33
gru_layer_size_2:
  value: 85
gru_layer_size_3:
  value: 63
learning_rate:
  value: 0.009599069072943795
lookback:
  value: 744
momentum:
  value: 0.9184209591699685
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
