wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 32
cnn_layer_size_1:
  value: 97
cnn_layer_size_2:
  value: 157
cnn_layer_size_3:
  value: 117
dataset:
  value: strib
dropout:
  value: 0.231495417114896
epochs:
  value: 25
gru_layer_size_1:
  value: 163
gru_layer_size_2:
  value: 152
gru_layer_size_3:
  value: 99
learning_rate:
  value: 0.0331747167365047
lookback:
  value: 744
momentum:
  value: 0.6350569265959602
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
