wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 112
cnn_layer_size_1:
  value: 105
cnn_layer_size_2:
  value: 67
cnn_layer_size_3:
  value: 74
dataset:
  value: strib
dropout:
  value: 0.1845357936746025
epochs:
  value: 25
gru_layer_size_1:
  value: 201
gru_layer_size_2:
  value: 101
gru_layer_size_3:
  value: 199
learning_rate:
  value: 0.03896813199932402
lookback:
  value: 744
momentum:
  value: 0.6830867443211333
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
