wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 161
cnn_layer_size_1:
  value: 144
cnn_layer_size_2:
  value: 105
cnn_layer_size_3:
  value: 36
dataset:
  value: strib
dropout:
  value: 0.0934218555120621
epochs:
  value: 25
gru_layer_size_1:
  value: 36
gru_layer_size_2:
  value: 62
gru_layer_size_3:
  value: 119
learning_rate:
  value: 0.013573657917683571
lookback:
  value: 744
momentum:
  value: 0.5840467808291915
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
