wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 107
cnn_layer_size_1:
  value: 89
cnn_layer_size_2:
  value: 52
cnn_layer_size_3:
  value: 45
dataset:
  value: kolding
dropout:
  value: 0.2722160418051974
epochs:
  value: 25
gru_layer_size_1:
  value: 60
gru_layer_size_2:
  value: 75
gru_layer_size_3:
  value: 176
learning_rate:
  value: 0.014346654394248926
lookback:
  value: 744
momentum:
  value: 0.6199037047603387
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
