wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 35
cnn_layer_size_1:
  value: 90
cnn_layer_size_2:
  value: 130
dropout:
  value: 0.09680960344471823
epochs:
  value: 50
gru_layer_size_1:
  value: 51
gru_layer_size_2:
  value: 255
learning_rate:
  value: 0.06096348868429373
lookback:
  value: 270.74976756853926
momentum:
  value: 0.8
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: adam
