wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 39
cnn_layer_size_1:
  value: 98
cnn_layer_size_2:
  value: 196
dropout:
  value: 0.43665605979710814
epochs:
  value: 50
gru_layer_size_1:
  value: 197
gru_layer_size_2:
  value: 39
learning_rate:
  value: 0.060179815106127715
lookback:
  value: 367.9839551304922
momentum:
  value: 0.95
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: rmsprop
