wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 164
cnn_layer_size_1:
  value: 44
cnn_layer_size_2:
  value: 79
dropout:
  value: 0.045452611523636
epochs:
  value: 50
gru_layer_size_1:
  value: 49
gru_layer_size_2:
  value: 48
learning_rate:
  value: 0.062107420320679216
lookback:
  value: 584.1004541803065
momentum:
  value: 0.9
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: rmsprop
