wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 34
cnn_layer_size_1:
  value: 38
cnn_layer_size_2:
  value: 248
dropout:
  value: 0.2595054780232043
epochs:
  value: 50
gru_layer_size_1:
  value: 100
gru_layer_size_2:
  value: 155
learning_rate:
  value: 0.053249612740154474
lookback:
  value: 386
momentum:
  value: 0.9
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
