wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 77
cnn_layer_size_1:
  value: 97
cnn_layer_size_2:
  value: 136
dropout:
  value: 0.0023026211820821874
epochs:
  value: 50
gru_layer_size_1:
  value: 89
gru_layer_size_2:
  value: 73
learning_rate:
  value: 0.04095932774528411
lookback:
  value: 650
momentum:
  value: 0.85
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: adam
