wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 99
cnn_layer_size_1:
  value: 50
cnn_layer_size_2:
  value: 89
dropout:
  value: 0.4881324923375092
epochs:
  value: 50
gru_layer_size_1:
  value: 35
gru_layer_size_2:
  value: 256
learning_rate:
  value: 0.06604772283819824
lookback:
  value: 649
momentum:
  value: 0.9
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: adam
