wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 203
cnn_layer_size_1:
  value: 62
cnn_layer_size_2:
  value: 102
dataset:
  value: kolding
dropout:
  value: 0.11977028677745097
epochs:
  value: 10
gru_layer_size_1:
  value: 62
gru_layer_size_2:
  value: 198
learning_rate:
  value: 0.017118033478074036
lookback:
  value: 744
momentum:
  value: 0.8661617678219562
num_cnn_layers:
  value: 0
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: d
