wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 254
cnn_layer_size_1:
  value: 67
cnn_layer_size_2:
  value: 107
dataset:
  value: strib
dropout:
  value: 0.45847686837230717
epochs:
  value: 10
gru_layer_size_1:
  value: 52
gru_layer_size_2:
  value: 188
learning_rate:
  value: 0.0309663952845563
lookback:
  value: 744
momentum:
  value: 0.34665938143263136
num_cnn_layers:
  value: 0
num_features:
  value: 9
num_gru_layers:
  value: 0
optimizer:
  value: d
