wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.8.3
      5: 0.10.28
      8:
      - 1
      - 3
      - 5
activation_cnn:
  desc: null
  value: relu
activation_gru:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 175
cnn_layer_size_1:
  desc: null
  value: 156
cnn_layer_size_2:
  desc: null
  value: 73
cnn_layer_size_3:
  desc: null
  value: 126
dataset:
  desc: null
  value: strib
dropout:
  desc: null
  value: 0.21593520780215705
epochs:
  desc: null
  value: 25
gru_layer_size_1:
  desc: null
  value: 37
gru_layer_size_2:
  desc: null
  value: 218
gru_layer_size_3:
  desc: null
  value: 149
learning_rate:
  desc: null
  value: 0.03630478461924794
lookback:
  desc: null
  value: 744
momentum:
  desc: null
  value: 0.9679976376365662
num_cnn_layers:
  desc: null
  value: 2
num_features:
  desc: null
  value: 9
num_gru_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: sgd
