wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 248
cnn_layer_size_1:
  value: 39
cnn_layer_size_2:
  value: 174
dropout:
  value: 0.3526781533415718
epochs:
  value: 50
gru_layer_size_1:
  value: 244
gru_layer_size_2:
  value: 190
learning_rate:
  value: 0.06175795516981232
lookback:
  value: 680
momentum:
  value: 0.95
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: adam
