wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 38
cnn_layer_size_1:
  value: 225
cnn_layer_size_2:
  value: 128
dropout:
  value: 0.31963665946425573
epochs:
  value: 50
gru_layer_size_1:
  value: 104
gru_layer_size_2:
  value: 238
learning_rate:
  value: 0.053036436782389416
lookback:
  value: 470
momentum:
  value: 0.8
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: adam
