wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 37
cnn_layer_size_1:
  value: 32
cnn_layer_size_2:
  value: 181
dropout:
  value: 0.4440781710876469
epochs:
  value: 50
gru_layer_size_1:
  value: 52
gru_layer_size_2:
  value: 208
learning_rate:
  value: 0.07789108069018007
lookback:
  value: 542
momentum:
  value: 0.95
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: rmsprop
