wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 133
cnn_layer_size_1:
  value: 233
cnn_layer_size_2:
  value: 44
dropout:
  value: 0.24295156749592733
epochs:
  value: 50
gru_layer_size_1:
  value: 94
gru_layer_size_2:
  value: 106
learning_rate:
  value: 0.0489416542430523
lookback:
  value: 569
momentum:
  value: 0.95
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: sgd
