wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 183
cnn_layer_size_1:
  value: 129
cnn_layer_size_2:
  value: 82
dropout:
  value: 0.11261000099545448
epochs:
  value: 50
gru_layer_size_1:
  value: 40
gru_layer_size_2:
  value: 38
learning_rate:
  value: 0.07911497407574514
lookback:
  value: 414
momentum:
  value: 0.9
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: adam
