wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 32
cnn_layer_size_1:
  value: 188
cnn_layer_size_2:
  value: 51
dropout:
  value: 0.2846871559925311
epochs:
  value: 50
gru_layer_size_1:
  value: 207
gru_layer_size_2:
  value: 154
learning_rate:
  value: 0.005971002603623766
lookback:
  value: 193
momentum:
  value: 0.95
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: adam
