wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 247
cnn_layer_size_1:
  value: 88
cnn_layer_size_2:
  value: 133
dropout:
  value: 0.20357324572128604
epochs:
  value: 50
gru_layer_size_1:
  value: 76
gru_layer_size_2:
  value: 102
learning_rate:
  value: 0.08804630995000742
lookback:
  value: 364
momentum:
  value: 0.9
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: rmsprop
