wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 227
cnn_layer_size_1:
  value: 70
cnn_layer_size_2:
  value: 106
dropout:
  value: 0.01530791982572427
epochs:
  value: 50
gru_layer_size_1:
  value: 51
gru_layer_size_2:
  value: 194
learning_rate:
  value: 0.024205150803738973
lookback:
  value: 718
momentum:
  value: 0.9
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
