wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 225
cnn_layer_size_1:
  value: 211
cnn_layer_size_2:
  value: 157
dropout:
  value: 0.4757026996014911
epochs:
  value: 50
gru_layer_size_1:
  value: 228
gru_layer_size_2:
  value: 56
learning_rate:
  value: 0.03638779782590248
lookback:
  value: 500
momentum:
  value: 0.95
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
