wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 247
cnn_layer_size_1:
  value: 191
cnn_layer_size_2:
  value: 128
dropout:
  value: 0.4676747098177177
epochs:
  value: 50
gru_layer_size_1:
  value: 156
gru_layer_size_2:
  value: 45
learning_rate:
  value: 0.011999687466323749
lookback:
  value: 187
momentum:
  value: 0.9
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 2
optimizer:
  value: sgd
