wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 126
cnn_layer_size_1:
  value: 37
cnn_layer_size_2:
  value: 187
dropout:
  value: 0.009393302344775645
epochs:
  value: 50
gru_layer_size_1:
  value: 127
gru_layer_size_2:
  value: 205
learning_rate:
  value: 0.044024628023275544
lookback:
  value: 666
momentum:
  value: 0.9
num_cnn_layers:
  value: 2
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: sgd
