wandb_version: 1

activation_cnn:
  value: relu
activation_gru:
  value: tanh
batch_size:
  value: 38
cnn_layer_size_1:
  value: 103
cnn_layer_size_2:
  value: 173
dropout:
  value: 0.37956133078684157
epochs:
  value: 50
gru_layer_size_1:
  value: 38
gru_layer_size_2:
  value: 43
learning_rate:
  value: 0.060396796100941376
lookback:
  value: 290.5496132440562
momentum:
  value: 0.95
num_cnn_layers:
  value: 1
num_features:
  value: 9
num_gru_layers:
  value: 1
optimizer:
  value: adam
